### ISSUE TITLE
Iterative threshold on 32 bit images

### ISSUE THREAD

**Issue by lguerard** [mcib3d/mcib3d-core#12]
Hi,

I'm trying to use the Iterative threshold on a 32-bit image and get errors.
Here is the call
```python
IT = TrackThreshold(volMin, volMax, minCont, step, step, thmin)
# use 32 bit
IT.setUse32bits(True)
#print(IT.use32bits)
# check threshold every step
tmethod = TrackThreshold.THRESHOLD_METHOD_VOLUME
IT.setMethodThreshold(tmethod)
# favours the edges
cri = TrackThreshold.CRITERIA_METHOD_MAX_VOLUME
# cri = TrackThreshold.CRITERIA_METHOD_MIN_ELONGATION
IT.setCriteriaMethod(cri)
# segment objects
impThresh = IT.segmentBest(imp_for_thresh, True)
```

and the errors
```
    impThresh = IT.segmentBest(imp_for_thresh, True)
	at mcib3d.image3d.IterativeThresholding.TrackThreshold.constantVoxelsHistogram(TrackThreshold.java:134)
	at mcib3d.image3d.IterativeThresholding.TrackThreshold.initHistogram(TrackThreshold.java:226)
	at mcib3d.image3d.IterativeThresholding.TrackThreshold.process(TrackThreshold.java:364)
	at mcib3d.image3d.IterativeThresholding.TrackThreshold.segmentBest(TrackThreshold.java:690)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.ClassCastException: java.lang.ClassCastException: [F cannot be cast to [S
```

I tried with and without the ```setUse32bits(True)``` and get the same thing. However, if I convert to 16bit before the threshold, it works.

**Comment by mcib3d** [comment]
Hi,

Sorry the function name is not very explicit, the 32-bits refer to the output label image, in case you will have more than 65,535 objects you need to create a 32-bits image as output instead of a 16-bits. 
The algorithm currently does not work with 32-bits images, since first we need to analyse the histogram and then decide the steps to take. 
In case of a 32 bits image I do not see how from one step to the next, it will basically mean checking all the pixel values. I need to think of a way to analyse 32-bits histogram, and of course, comments or ideas are appreciated.

Best
